### ISSUE TITLE
Request to create and add Logo for FREE_SPELL

### ISSUE THREAD

**Issue by MD-DILDAR-MANDAL** [MD-DILDAR-MANDAL/FREE_SPELL#16]
**Logo Format:**
- Ensure that the logo is in a standard image format, such as PNG or SVG.

**Placement:**
- The logo should be displayed prominently on the readme.md , near the project name or description.

 Please let us know if any additional information or actions are required from our end to expedite this process.

**Comment by cjstyles6** [comment]
@MD-DILDAR-MANDAL can i work on this issue

**Comment by MD-DILDAR-MANDAL** [comment]
Yes you can work @cjstyles6

**Comment by cjstyles6** [comment]
Alright

**Comment by MD-DILDAR-MANDAL** [comment]
Any updates on logo @cjstyles6

**Comment by MD-DILDAR-MANDAL** [comment]
Ok it's fine , take your time.

**Comment by cjstyles6** [comment]
@MD-DILDAR-MANDAL am done making the logo,should i just drop it here?

**Comment by MD-DILDAR-MANDAL** [comment]
- Create a img folder in the FREE_SPELL repo
- Add the logo in the img folder
- Open a pull request

**Comment by cjstyles6** [comment]
Done
