### ISSUE TITLE
Update important link

### ISSUE THREAD

**Issue by no-More-Gem** [MD-DILDAR-MANDAL/FREE_SPELL#5]
## Description
 The links are not clickable
[changes should be done here](https://github.com/MD-DILDAR-MANDAL/FREE_SPELL/blob/3918e17724788888128cddea6b73b07e30ae20fd/Resources/Important%20Links.md?plain=1#L7-L15)

**Comment by MD-DILDAR-MANDAL** [comment]
File updated and clickable links added
